name: YAML Lint
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Yamllint Github Action
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Set up Python 3.8
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.8
      #     architecture: 'x64'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install yamllint
      # - name: Validate Manifests
      #   run: ./hack/validate_yaml.sh
